### ISSUE TITLE
[Feat] SVG Components

### ISSUE THREAD

**Issue by devpla** [hoxc/movie#21]
## 💡 개요

- 예쁜 SVG들을 모아모아 컴포넌트로 만들자.

<br/>

## 📋 진행상황

- [x] IconBase 구축
- [x] SVG 컴포넌트화

<br/>

## 🗨 의견 

-

**Comment by seokzin** [comment]
이것도 프로젝트 중에 같이 진행 해버렸다.
현재 width, height, viewbox 정도만 props로 관리 하는데
추후 stroke color, width도 props로 관리하면 좋을 것 같다!
