### ISSUE TITLE
[Feat] Global Font 설치

### ISSUE THREAD

**Issue by devpla** [hoxc/movie#23]
## 💡 개요

- 글로벌 폰트를 설치하자.
- 기왕이면 서브셋 폰트로 최적화 -> 포스팅까지

<br/>

## 📋 진행상황

- [x] 글로벌 폰트 CSS 선언

<br/>

## 🗨 의견 

-

**Comment by seokzin** [comment]
원래 서브셋(최적화) 폰트 도입을 고려 했는데 우리 서비스가 아직은 가볍기 때문에 이른 도입 패쓰
다만 나중에 리팩토링할 때는 폰트 도입을 고려해보겠음!
