### ISSUE TITLE
[Feat] 메인페이지 레이아웃

### ISSUE THREAD

**Issue by devpla** [hoxc/movie#59]
## 💡 개요

- 메인 페이지 레이아웃을 구상하자

<br/>

## 📋 진행상황

- [ ] 탑 배너 레이아웃
- [ ] 추천 영화 레이아웃
- [ ] 영화 요약된 리스트

<br/>

## 🗨 의견 

-

**Comment by seokzin** [comment]
랜덤 무비 스르륵 흘러가는 인터랙션 랜딩에 넣기!
