### ISSUE TITLE
[WIP] 임시 배포

### ISSUE THREAD

**Issue by seokzin** [hoxc/movie#7]
## 💡 개요

- 테스트를 위해 빠른 배포 및 임시 도메인 연결

<br/>

## 📋 진행상황

- [x] 배포 서비스 선택 (Django) -> AWS Lambda
- [x] ~~임시 도메인 생성 (보류: 무료 도메인이 별로)~~
- [x] ~~배포! (보류: 완성 후 배포하는 게 맞음)~~

<br/>

## 🗨 의견 

- 카드에서 돈 나갈 예정 ! ! !
- Timezone 설정이 이쯤에서 필요하려나..?
- AWS 쓰려 했다가,, 서버에 시간 많이 쏟을까봐 Heroku 생각 중

**Comment by seokzin** [comment]
우선 중단!
- AWS : 과금 이슈가 있음
- heroku : 요구 라이브러리가 많아서 임시 배포로써는 부적합
- pythonanywhere : TODO

**Comment by devpla** [comment]
pythonanywhere는 무거우면 잘 터지니 주의..

**Comment by seokzin** [comment]
Vue랑 합쳐서 빌드 하는 게 너무 어려워서 미루고 있어,,

**Comment by seokzin** [comment]
수업 때 알려준 Back(AWS) Front(Netlify) 도입을 진행해보자!
다만 Back 배포가 서버리스 형태가 맞는지는 공부 필요!
