### ISSUE TITLE
[Feat] Django 프로젝트 생성 및 설정

### ISSUE THREAD

**Issue by devpla** [hoxc/movie#8]
## 💡 개요

- Django 프로젝트 생성, 기본 세팅

<br/>

## 📋 진행상황

- [x] Django 프로젝트 시작
- [x] `settings.py` 설정

<br/>

## 🗨 의견 

- ERD는 아직 확정 안해서 app은 생성 X
- User model 확정 후 진행

**Comment by seokzin** [comment]
Django + Vue 형태의 디렉토리 구조부터 협의!
